---

- name: Service start/stop/restart
  hosts: all
  gather_facts: false
  become: true
  vars_prompt:
    - name: service_name
      prompt: Service name?
      private: false
    - name: service_state
      prompt: Service state (started|stopped|restarted|reloaded)?
      private: false
  tasks:
    - name: "Ensure {{ service_name }} is {{ service_state }}"
      service:
        name: "{{ service_name }}"
        state: "{{ service_state }}"
